name: CWCFlutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^3.2.0
  sqflite: ^1.2.0
  path: ^1.6.4
  bubble_bottom_bar: ^1.2.0
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  flip_card: ^0.4.4
  flutter_staggered_grid_view: ^0.3.0


dev_dependencies:
  google_fonts: ^1.1.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/simple.png
    - images/dp_default.png
    - images/notification.png
    - images/calendar.png
    - images/festival.png
    - images/food.png
    - images/map.png
    - images/setting.png
    - images/todo.png
    - images/black_widow.png
    - images/captain_america.png
    - images/hulk.png
    - images/iron_man.png
    - images/loki.png
    - images/nick_fury.png
    - images/thor.png
    - images/war_machine.png
    - images/image1.jpg
    - images/image2.jpg
    - images/slider_money_gif.gif
    - images/slider_smiley_gif.gif
    - images/slider_star_gif.gif
    - images/images.jfif
    - images/img1.jfif
    - images/hellowel.jfif
    - images/helloww.jfif
    - images/hell.jfif
    - images/hrr.jfif
    - images/tata.jfif
    - images/bacgrr.jfif
    - images/dollar.jfif
    - images/orangii.jfif
    - images/orafl.jfif
    - images/orange.jfif
    - images/orange sunset.jfif
    - images/blockorange.jfif
    #-

   # - images/images(2).jfif
   # - images/images(3).jfif

   # - images/images(4).jfif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
